version: 0.2

phases:
  install:
    runtime-versions:
      java:  corretto17
    commands:
        - yum update -y
  build:
    commands:
        - mvn clean package
artifacts:
  files:
        - target/*.war
        - appspec.yaml
        - scripts/*
